# The YAML configuration file for generating Dockerfile of image phpswoole/swoole:5.0.1.
# For technical details of the configuration file, please check comments and sample configurations in file /config.yml.
#
status: "released"
php:
  - "8.0.25"
  - "8.1.12"
  - "8.2.0"
image:
  composer:
    version: "2.4.4"
  php_extensions:
    redis:
      version: "5.3.7"
      configureoptions: "enable-redis-igbinary=\"no\" enable-redis-lzf=\"no\" enable-redis-zstd=\"no\""
      enabled: true
