# The YAML configuration file for generating Dockerfile of image phpswoole/swoole:5.1.2.
# For technical details of the configuration file, please check comments and sample configurations in file /config.yml.
#
status: "released"
php:
  - "8.0.30"
  - "8.1.27"
  - "8.2.15"
  - "8.3.2"
image:
  composer:
    version: "2.6.6"
  php_extensions:
    redis:
      version: "6.0.2"
      configureoptions: "enable-redis-igbinary=\"no\" enable-redis-lzf=\"no\" enable-redis-zstd=\"no\""
      enabled: true
