# The YAML configuration file for generating Dockerfile of image phpswoole/swoole:6.0.0-beta.
# For technical details of the configuration file, please check comments and sample configurations in file /config.yml.
#
status: "under development"
php:
  - "8.0.30"
  - "8.1.30"
  - "8.2.25"
  - "8.3.13"
image:
  composer:
    version: "2.8.2"
  php_extensions:
    redis:
      version: "6.1.0"
      configureoptions: "enable-redis-igbinary=\"no\" enable-redis-lzf=\"no\" enable-redis-zstd=\"no\""
      enabled: true
