# The YAML configuration file for generating Dockerfile of image phpswoole/swoole:6.0.0-alpha.
# For technical details of the configuration file, please check comments and sample configurations in file /config.yml.
#
status: "under development"
php:
  - "8.0.30"
  - "8.1.29"
  - "8.2.20"
  - "8.3.8"
image:
  composer:
    version: "2.7.7"
  php_extensions:
    redis:
      version: "6.0.2"
      configureoptions: "enable-redis-igbinary=\"no\" enable-redis-lzf=\"no\" enable-redis-zstd=\"no\""
      enabled: true
