version: '3'

services:
  app:
    build: .
    environment:
      PHP_IDE_CONFIG: "serverName=swoole"
      XDEBUG_CONFIG: idekey=PHPSTORM remote_host=host.docker.internal remote_port=9000
    ports:
      - 80:9501
