version: '3'

services:
  app:
    build: .
    environment:
      PHP_IDE_CONFIG: "serverName=swoole"
      XDEBUG_SESSION: "PHPSTORM"
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9000
    ports:
      - 80:9501
